name: mlflow_demos
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.3
  - pip==21.0.1
  - pip:
      - mlflow==1.14.0
      - pandas==1.2.2
      - numpy==1.20.1
      - scikit-learn==0.24.1